name: kws
channels:
  - defaults
dependencies:
  - python=3.8.18
  - cython=3.0.6
  - loguru=0.5.3
  - numba=0.58.1
  - numpy=1.24.3
  - pillow=10.0.1
  - pip=23.3.1
  - requests=2.31.0
  - scikit-learn=1.3.0
  - scipy=1.10.1
  - pydantic=2.5.3
  - pytest=7.4.0
  - pip:
      - pyyaml==6.0.1
      - librosa==0.10.1
      - python-speech-features==0.6
      - torch==2.0.1
      - torchaudio==2.0.2
