# parameters for training
background_volume: 0.1
background_frequency: 0.8
time_shift_ms: 50.0
sample_rate: 16000
clip_duration: 1000
use_background_noise: True

silence_percentage: 10.0
unknown_percentage: 10.0
testing_percentage: 10.0
validation_percentage: 10.0

wanted_words:
  - yes
  - no
  - up
  - down
  - left
  - right
  - on
  - off
  - stop
  - go
